[fix] warnings in search tests
```
In file included from /seqan3/test/unit/search/fm_index_test.cpp:40:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/search/fm_index_test.cpp:114:5:   required from ‘void fm_index_test_size_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::bi_fm_index<std::vector<seqan3::aa27> >]’
/seqan3/test/unit/search/fm_index_test.cpp:107:1:   required from here
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1421:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~

```