[fix] warnings in search tests
```
In file included from /seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:47,
                 from /seqan3/include/seqan3/search/fm_index/all.hpp:73,
                 from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:44:
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp: In instantiation of ‘seqan3::bi_fm_index_iterator<index_t>::bi_fm_index_iterator(const index_t&) [with index_t = seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits>]’:
/seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:306:22:   required from ‘seqan3::bi_fm_index<text_t, index_traits_t>::iterator_type seqan3::bi_fm_index<text_t, index_traits_t>::begin() const [with text_t = std::vector<seqan3::dna4>; index_traits_t = seqan3::bi_fm_index_default_traits; seqan3::bi_fm_index<text_t, index_traits_t>::iterator_type = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:233:44:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:148:15: error: ‘seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::depth’ will be initialized after [-Werror=reorder]
     size_type depth; // equal for both iterators. only stored once
               ^~~~~
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:120:15: error:   ‘seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::size_type seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::fwd_lb’ [-Werror=reorder]
     size_type fwd_lb;
               ^~~~~~
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:272:5: error:   when initialized here [-Werror=reorder]
     bi_fm_index_iterator(index_t const & _index) noexcept : index(&_index), depth(0),
     ^~~~~~~~~~~~~~~~~~~~
```