[TEST] two_dimensional_matrix_test use original fix again
```
/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp: In instantiation of ‘std::vector<T> create_matrix_storage() [with score_type = __vector(1) int; seqan3::detail::matrix_major_order order = seqan3::detail::matrix_major_order::row]’:
/seqan3-build/gcc-10-std17-debug/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:460:40:   recursively required from ‘gtest_suite_iterator_fixture_::compare_geq<seqan3::detail::two_dimensional_matrix<__vector(1) int, std::allocator<__vector(1) int>, seqan3::detail::matrix_major_order::column> >::compare_geq()’
/seqan3-build/gcc-10-std17-debug/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:460:40:   required from ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = gtest_suite_iterator_fixture_::compare_geq<seqan3::detail::two_dimensional_matrix<__vector(1) int, std::allocator<__vector(1) int>, seqan3::detail::matrix_major_order::column> >]’
/seqan3-build/gcc-10-std17-debug/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:460:9:   required from here
/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp:43:15: error: invalid type ‘__vector(1) int’ as initializer for a vector of type ‘const __vector(1) int’
   43 |     storage_t row_wise
      |               ^~~~~~~~
/seqan3/test/unit/alignment/matrix/detail/two_dimensional_matrix_test.cpp:50:15: error: invalid type ‘__vector(1) int’ as initializer for a vector of type ‘const __vector(1) int’
   50 |     storage_t column_wise
      |               ^~~~~~~~~~~
```