[fix] warnings in alignment tests
```
In file included from /seqan3/test/unit/alignment/pairwise/alignment_selector_test.cpp:35:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/alignment/pairwise/alignment_selector_test.cpp:73:9:   required from here
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1421:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
```

```
In file included from /seqan3/include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp:46,
                 from /seqan3/test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp:43:
/seqan3/include/seqan3/alignment/pairwise/execution/alignment_range.hpp: In instantiation of ‘seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)> [with auto:1 = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>*]’:
/usr/include/c++/8.2.1/type_traits:2283:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>&; _Args = {seqan3::detail::alignment_executor_two_way<std::vector<foo, std::allocator<foo> >&, foo_selector, seqan3::detail::execution_handler_sequential>*&}]’
/usr/include/c++/8.2.1/type_traits:2294:55:   required from ‘struct std::__result_of_impl<false, false, seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>&, seqan3::detail::alignment_executor_two_way<std::vector<foo, std::allocator<foo> >&, foo_selector, seqan3::detail::execution_handler_sequential>*&>’
/usr/include/c++/8.2.1/type_traits:2617:12:   recursively required by substitution of ‘template<class _Result, class _Ret> struct std::__is_invocable_impl<_Result, _Ret, std::__void_t<typename _Result::type> > [with _Result = std::__invoke_result<seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>&, seqan3::detail::alignment_executor_two_way<std::vector<foo, std::allocator<foo> >&, foo_selector, seqan3::detail::execution_handler_sequential>*&>; _Ret = void]’
/usr/include/c++/8.2.1/type_traits:2617:12:   required from ‘struct std::__is_invocable<seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>&, seqan3::detail::alignment_executor_two_way<std::vector<foo, std::allocator<foo> >&, foo_selector, seqan3::detail::execution_handler_sequential>*&>’
/usr/include/c++/8.2.1/bits/shared_ptr_base.h:1114:40:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(_Yp*, _Deleter) [with _Yp = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>; _Deleter = seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>; <template-parameter-2-3> = void; _Tp = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>; __gnu_cxx::_Lock_policy _Lp = (__gnu_cxx::_Lock_policy)2]’
/usr/include/c++/8.2.1/bits/shared_ptr.h:157:48:   required from ‘std::shared_ptr<_Tp>::shared_ptr(_Yp*, _Deleter) [with _Yp = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>; _Deleter = seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]::<lambda(auto:1)>; <template-parameter-2-3> = void; _Tp = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]’
/seqan3/include/seqan3/alignment/pairwise/execution/alignment_range.hpp:186:64:   required from ‘seqan3::alignment_range<range_buffer_t>::alignment_range(range_buffer_t&) [with range_buffer_t = seqan3::detail::alignment_executor_two_way<std::vector<foo>&, foo_selector, seqan3::detail::execution_handler_sequential>]’
/seqan3/include/seqan3/alignment/pairwise/execution/alignment_executor_two_way.hpp:130:45:   required from ‘seqan3::alignment_range<seqan3::detail::alignment_executor_two_way<align_instance_rng_t, alignment_selector_t, execution_handler_t> > seqan3::detail::alignment_executor_two_way<align_instance_rng_t, alignment_selector_t, execution_handler_t>::range() [with align_instance_rng_t = std::vector<foo>&; alignment_selector_t = foo_selector; execution_handler_t = seqan3::detail::execution_handler_sequential]’
/seqan3/test/unit/alignment/pairwise/execution/alignment_executor_two_way_test.cpp:77:32:   required from here
/seqan3/include/seqan3/alignment/pairwise/execution/alignment_range.hpp:186:46: error: unused parameter ‘ptr’ [-Werror=unused-parameter]
         range_buffer{&_range_buffer, [](auto ptr) { /*no-op*/ }}
                                         ~~~~~^~~
```

```
In file included from /seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:6:
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp: In instantiation of ‘seqan3::detail::pairwise_alignment_edit_distance_unbanded<database_t, query_t, align_config_t, traits_t>::pairwise_alignment_edit_distance_unbanded(database_t&&, query_t&&, align_config_t) [with database_t = std::vector<seqan3::dna4>&; query_t = std::vector<seqan3::dna4>&; align_config_t = seqan3::detail::configuration<seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&; traits_t = test_traits_type<unsigned char>]’:
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:161:10:   required from ‘auto edit_distance(database_t&&, query_t&&, align_cfg_t&&) [with word_type = unsigned char; database_t = std::vector<seqan3::dna4>&; query_t = std::vector<seqan3::dna4>&; align_cfg_t = seqan3::detail::configuration<seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&]’
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:190:46:   required from ‘void gtest_case_edit_distance_unbanded_::score_matrix<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = param<(& seqan3::fixture::global::edit_distance::unbanded::dna4_02), unsigned char>]’
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:181:1:   required from here
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp:270:19: error: narrowing conversion of ‘-1’ from ‘int’ to ‘seqan3::detail::pairwise_alignment_edit_distance_unbanded<std::vector<seqan3::dna4>&, std::vector<seqan3::dna4>&, seqan3::detail::configuration<seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&, test_traits_type<unsigned char> >::word_type’ {aka ‘unsigned char’} inside { } [-Wnarrowing]
         word_type vp0{~word_type{0}};
                   ^~~
```

```
In file included from /seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:6:
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp: In instantiation of ‘bool seqan3::detail::pairwise_alignment_edit_distance_unbanded<database_t, query_t, align_config_t, traits_t>::small_patterns() [with database_t = std::vector<seqan3::aa27>&; query_t = std::vector<seqan3::aa27>&; align_config_t = seqan3::detail::configuration<seqan3::detail::align_config_max_error, seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&; traits_t = test_traits_type<short unsigned int>]’:
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp:414:13:   required from ‘void seqan3::detail::pairwise_alignment_edit_distance_unbanded<database_t, query_t, align_config_t, traits_t>::_compute() [with database_t = std::vector<seqan3::aa27>&; query_t = std::vector<seqan3::aa27>&; align_config_t = seqan3::detail::configuration<seqan3::detail::align_config_max_error, seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&; traits_t = test_traits_type<short unsigned int>]’
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp:431:9:   required from ‘result_type& seqan3::detail::pairwise_alignment_edit_distance_unbanded<database_t, query_t, align_config_t, traits_t>::operator()(result_type&) [with result_type = std::tuple<>; database_t = std::vector<seqan3::aa27>&; query_t = std::vector<seqan3::aa27>&; align_config_t = seqan3::detail::configuration<seqan3::detail::align_config_max_error, seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&; traits_t = test_traits_type<short unsigned int>]’
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:164:14:   required from ‘auto edit_distance(database_t&&, query_t&&, align_cfg_t&&) [with word_type = short unsigned int; database_t = std::vector<seqan3::aa27>&; query_t = std::vector<seqan3::aa27>&; align_cfg_t = seqan3::detail::configuration<seqan3::detail::align_config_max_error, seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&]’
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:236:46:   required from ‘void gtest_case_edit_distance_unbanded_::trace<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = param<(& seqan3::fixture::global::edit_distance::max_errors::unbanded::aa27_01T_e255), short unsigned int>]’
/seqan3/test/unit/alignment/pairwise/edit_distance_unbanded_test.cpp:227:1:   required from here
/seqan3/include/seqan3/alignment/pairwise/edit_distance_unbanded.hpp:510:24: error: comparison of integer expressions of different signedness: ‘seqan3::detail::pairwise_alignment_edit_distance_unbanded<std::vector<seqan3::aa27>&, std::vector<seqan3::aa27>&, seqan3::detail::configuration<seqan3::detail::align_config_max_error, seqan3::detail::align_config_gap<seqan3::gap_scheme<signed char> >, seqan3::detail::align_config_score<seqan3::nucleotide_scoring_scheme<signed char> >, seqan3::detail::align_config_global>&, test_traits_type<short unsigned int> >::score_type’ {aka ‘int’} and ‘size_t’ {aka ‘long unsigned int’} [-Werror=sign-compare]
             if (_score <= max_errors && on_hit())
                 ~~~~~~~^~~~~~~~~~~~~
```