[FIX] clang+gcc9: aligned_allocator: clang does not support __cpp_sized_deallocation by default
```
/seqan3/include/seqan3/utility/container/aligned_allocator.hpp:180:13: error: no matching function for call to 'operator delete'
            ::operator delete(p, bytes_to_deallocate);
            ^~~~~~~~~~
```

https://github.com/pybind/pybind11/issues/1604#issuecomment-459796241
shows how to enable this.