[FIX] clang+gcc9: error: variable has incomplete type
```
/seqan3/include/seqan3/alignment/decorator/gap_decorator.hpp:206:46: error: variable has incomplete type 'const seqan3::gap_decorator::const_iterator' (aka 'const seqan3::gap_decorator::gap_decorator_iterator')
    iterator insert_gap(const_iterator const it, size_type const count = 1)
                                             ^
```

The problem here is that insert_gap is non-dependant (in two-phase lookup) and must be a complete type at that point which it isn't (it is just forward declared and the real definition happens later outside the class).

To fix this we have multiple options:

* define insert_gap, etc functions outside, too (but after const_iterator) (same API!)
* make function dependant by using a defaulted template argument
  (semantically the same API, but syntactical more convoluted and harder to understand)
  ```cpp
  template <typename const_iterator_t = const_iterator>
  iterator insert_gap(std::type_identity_t<const_iterator_t> const it, size_type const count = 1)
  ```
* make const_iterator a dependant name, by introducing a template argument
  (route chosen here, same API and easier to understand; might be weird, why we introduce a template argument that only has one value)