[fix] warnings in search tests
```
In file included from /seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp:46,
                 from /seqan3/include/seqan3/search/algorithm/configuration/all.hpp:49,
                 from /seqan3/include/seqan3/search/algorithm/all.hpp:91,
                 from /seqan3/test/unit/search/search_test.cpp:40:
/seqan3/include/seqan3/search/algorithm/configuration/utility.hpp: In instantiation of ‘constexpr bool seqan3::contains(const seqan3::detail::configuration<configs_t ...>&) [with seqan3::search_cfg::id e = (seqan3::search_cfg::id)0; cfg_elements_t = {seqan3::detail::search_config_max_error_rate}]’:
/seqan3/include/seqan3/search/algorithm/search.hpp:84:54:   required from ‘auto seqan3::search(const index_t&, queries_t&&, const configuration_t&) [with index_t = seqan3::bi_fm_index<std::vector<seqan3::dna4> >; queries_t = const std::vector<std::vector<seqan3::dna4> >&; configuration_t = seqan3::detail::configuration<seqan3::detail::search_config_max_error_rate>]’
/seqan3/test/unit/search/search_test.cpp:125:5:   required from ‘void search_test_multiple_queries_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::bi_fm_index<std::vector<seqan3::dna4> >]’
/seqan3/test/unit/search/search_test.cpp:119:1:   required from here
/seqan3/include/seqan3/search/algorithm/configuration/utility.hpp:280:74: error: unused parameter ‘cfg’ [-Werror=unused-parameter]
 constexpr bool contains(detail::configuration<cfg_elements_t...> const & cfg) noexcept
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

```