[FIX] clang+gcc9: error: no matching member function for call to 'read_field'
```
/seqan3/include/seqan3/io/sam_file/format_bam.hpp:420:5: error: no matching member function for call to 'read_field'
    read_field(stream_view | detail::take_exactly_or_throw(core.l_read_name - 1), id); // field::id
    ^~~~~~~~~~
```

The problem is that clang can't inherit constrained functions, see
https://bugs.llvm.org/show_bug.cgi?id=51544.

The fix is to give all `read_field` functions unique names, this
arguably makes it also easier to understand which "parsing" algorithm is
being called.