[FIX] gcc-11: std::views::drop expects std::ranges::range_difference_t<urng_t> (#2528)
* [FIX] gcc-11: std::views::drop expects std::ranges::range_difference_t<urng_t>

```
seqan3/include/seqan3/range/views/drop.hpp:95:49: error: no match for ‘operator|’ (operand types are ‘std::ranges::ref_view<std::__cxx11::list<seqan3::dna4> >’ and ‘std::ranges::views::__adaptor::_Partial<std::ranges::views::_Drop, long unsigned int>’)
   95 |             return std::forward<urng_t>(urange) | std::views::drop(drop_size);
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

* Apply suggestions from code review