[FIX] clang+gcc9: error: template template argument has different template parameters than its corresponding template template parameter
```
seqan3/include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp:339:57: error: template template argument has different template parameters than its corresponding template template parameter
        requires is_type_specialisation_of_v<derived_t, basic_iterator> && (other_order == order)
                                                        ^
/home/marehr/develope/seqan3/include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp:75:20: note: template parameter has a different kind in template argument
    template <bool const_range>
                   ^
```