[TEST] test_sized_sentinel<output_iterator> might not fulfill std::semiregular
`std::ostream_iterator<char>` does not have a default constructor and
thus `test_sized_sentinel<...>` can't be `std::semiregular`.

```
/seqan3/test/unit/std/concept/iterator_test.cpp:95:25: error: static assertion failed
   95 |     static_assert((std::sentinel_for<test_sized_sentinel<
      |                   ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                           output_iterator>,
      |                                           ~~~~~~~~~~~~~~~~~
   97 |                                           output_iterator>));
      |                                           ~~~~~~~~~~~~~~~~~
/seqan3/test/unit/std/concept/iterator_test.cpp:95:25: note: constraints not satisfied
In file included from /opt/gcc/gcc-git/include/c++/12.0.0/compare:39,
                 from /opt/gcc/gcc-git/include/c++/12.0.0/bits/stl_pair.h:65,
                 from /opt/gcc/gcc-git/include/c++/12.0.0/bits/stl_algobase.h:64,
                 from /opt/gcc/gcc-git/include/c++/12.0.0/memory:63,
                 from /seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/gtest.h:57,
                 from /seqan3/test/unit/std/concept/iterator_test.cpp:8:
/opt/gcc/gcc-git/include/c++/12.0.0/concepts:136:13:   required for the satisfaction of ‘constructible_from<_Tp>’ [with _Tp = test_sized_sentinel<std::ostream_iterator<char, char, std::char_traits<char> > >]
/opt/gcc/gcc-git/include/c++/12.0.0/concepts:141:13:   required for the satisfaction of ‘default_initializable<_Tp>’ [with _Tp = test_sized_sentinel<std::ostream_iterator<char, char, std::char_traits<char> > >]
/opt/gcc/gcc-git/include/c++/12.0.0/concepts:256:13:   required for the satisfaction of ‘semiregular<_Sent>’ [with _Sent = test_sized_sentinel<std::ostream_iterator<char, char, std::char_traits<char> > >]
/opt/gcc/gcc-git/include/c++/12.0.0/concepts:137:30: note: the expression ‘is_constructible_v<_Tp, _Args ...> [with _Tp = test_sized_sentinel<std::ostream_iterator<char, char, std::char_traits<char> > >; _Args = {}]’ evaluated to ‘false’
  137 |       = destructible<_Tp> && is_constructible_v<_Tp, _Args...>;
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```