[fix] warnings in search tests (#628)
* [fix] warnings in search tests

```
In file included from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:42:
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp: In instantiation of ‘auto seqan3::detail::search_scheme_block_info(const search_scheme_t&, size_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; size_t = long unsigned int]’:
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:222:65:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:118:45: error: narrowing conversion of ‘(((long unsigned int)query_length) % 1)’ from ‘long unsigned int’ to ‘uint8_t’ {aka ‘unsigned char’} inside { } [-Werror=narrowing]
     uint8_t const rest        {query_length % blocks};
                                ~~~~~~~~~~~~~^~~~~~~~
```

* [fix] warnings in search tests

```
In file included from /seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:47,
                 from /seqan3/include/seqan3/search/fm_index/all.hpp:73,
                 from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:44:
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp: In instantiation of ‘seqan3::bi_fm_index_iterator<index_t>::bi_fm_index_iterator(const index_t&) [with index_t = seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits>]’:
/seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:306:22:   required from ‘seqan3::bi_fm_index<text_t, index_traits_t>::iterator_type seqan3::bi_fm_index<text_t, index_traits_t>::begin() const [with text_t = std::vector<seqan3::dna4>; index_traits_t = seqan3::bi_fm_index_default_traits; seqan3::bi_fm_index<text_t, index_traits_t>::iterator_type = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:233:44:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:148:15: error: ‘seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::depth’ will be initialized after [-Werror=reorder]
     size_type depth; // equal for both iterators. only stored once
               ^~~~~
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:120:15: error:   ‘seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::size_type seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >::fwd_lb’ [-Werror=reorder]
     size_type fwd_lb;
               ^~~~~~
/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:272:5: error:   when initialized here [-Werror=reorder]
     bi_fm_index_iterator(index_t const & _index) noexcept : index(&_index), depth(0),
     ^~~~~~~~~~~~~~~~~~~~
```

* [fix] warnings in search tests

```
In file included from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:42:
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp: In instantiation of ‘bool seqan3::detail::search_ss(iterator_t, query_t&, typename iterator_t::size_type, typename iterator_t::size_type, uint8_t, uint8_t, bool, const search_t&, const blocks_length_t&, seqan3::detail::search_param, delegate_t&&) [with bool abort_on_hit = false; iterator_t = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; query_t = std::vector<seqan3::dna4>; search_t = seqan3::detail::search<1>; blocks_length_t = std::array<long unsigned int, 1>; delegate_t = test_search_hamming(auto:23, const text_t&, const auto:24&, uint64_t, const std::vector<unsigned char>&, time_t, const auto:25&, const auto:26&, uint64_t) [with text_t = std::vector<seqan3::dna4>; auto:23 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; auto:24 = seqan3::detail::search<1>; auto:25 = std::array<long unsigned int, 1>; auto:26 = std::vector<long unsigned int>; uint64_t = long unsigned int; time_t = long int]::<lambda(const auto:28&)>&; typename iterator_t::size_type = long unsigned int; uint8_t = unsigned char]’:
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:161:29:   required from ‘void test_search_hamming(auto:23, const text_t&, const auto:24&, uint64_t, const std::vector<unsigned char>&, time_t, const auto:25&, const auto:26&, uint64_t) [with text_t = std::vector<seqan3::dna4>; auto:23 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; auto:24 = seqan3::detail::search<1>; auto:25 = std::array<long unsigned int, 1>; auto:26 = std::vector<long unsigned int>; uint64_t = long unsigned int; time_t = long int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:233:44:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:407:45: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
     else if ((max_error_left_in_block == 0) && (rb - lb - 1 != blocks_length[block_id]) ||
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

* [fix] warnings in search tests

```
In file included from /seqan3/test/unit/search/fm_index_test.cpp:40:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/search/fm_index_test.cpp:114:5:   required from ‘void fm_index_test_size_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::bi_fm_index<std::vector<seqan3::aa27> >]’
/seqan3/test/unit/search/fm_index_test.cpp:107:1:   required from here
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1421:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~

```

* [fix] warnings in search tests

```
In file included from /seqan3/include/seqan3/search/algorithm/configuration/all.hpp:49,
                 from /seqan3/include/seqan3/search/algorithm/all.hpp:91,
                 from /seqan3/test/unit/search/search_test.cpp:40:
/seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp: In instantiation of ‘constexpr auto seqan3::detail::search_config_max_error_adaptor::invoke(configuration_t&&, error_types_t&& ...) const [with configuration_t = seqan3::detail::configuration<>; error_types_t = {const seqan3::search_cfg::substitution<unsigned char>&}]’:
/seqan3/include/seqan3/core/algorithm/configuration.hpp:394:93:   required from ‘constexpr auto seqan3::detail::configuration_fn_base<derived_fn_t>::operator()(configuration_t&&, args_t&& ...) const requires  is_algorithm_configuration_v<typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::remove_cvref_t> [with configuration_t = seqan3::detail::configuration<>; args_t = {const seqan3::search_cfg::substitution<unsigned char>&}; derived_fn_t = seqan3::detail::search_config_max_error_adaptor]’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:514:27:   required from ‘constexpr auto seqan3::detail::configuration_fn_proxy<derived_t, args_t>::explode(configuration_t&&, std::index_sequence<Is ...>) const & [with configuration_t = seqan3::detail::configuration<>; long unsigned int ...Is = {0}; derived_t = seqan3::detail::search_config_max_error_adaptor; args_t = {seqan3::search_cfg::substitution<unsigned char>}; std::index_sequence<Is ...> = std::integer_sequence<long unsigned int, 0>]’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:528:105:   required from ‘constexpr auto seqan3::detail::configuration_fn_proxy<derived_t, args_t>::operator()(configuration_t&&) && [with configuration_t = seqan3::detail::configuration<>; derived_t = seqan3::detail::search_config_max_error_adaptor; args_t = {seqan3::search_cfg::substitution<unsigned char>}]’
/usr/include/c++/8.2.1/type_traits:2283:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >; _Args = {seqan3::detail::configuration<>}]’
/usr/include/c++/8.2.1/type_traits:2294:55:   required from ‘struct std::__result_of_impl<false, false, seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/usr/include/c++/8.2.1/type_traits:2299:12:   required from ‘struct std::__invoke_result<seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/usr/include/c++/8.2.1/type_traits:2685:12:   required from ‘struct std::invoke_result<seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:299:1:   required by substitution of ‘template<class cfg_fn_t>  requires  is_type_specialisation_of_v<typename std::remove_reference::remove_reference_t, seqan3::detail::configuration_fn_proxy> or is_base_of_v<seqan3::detail::configuration_fn_base<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::remove_cvref_t> seqan3::detail::configuration(cfg_fn_t&&)-> seqan3::detail::configuration<typename meta::v1::detail::front_<typename seqan3::detail::tuple_type_list<typename std::invoke_result<typename std::remove_reference<_Tp>::type, seqan3::detail::configuration<> >::type::base_type>::type>::type> [with cfg_fn_t = seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >]’
/seqan3/test/unit/search/search_test.cpp:190:68:   required from here
/seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp:126:30: error: narrowing conversion of ‘(int)std::min<int>(255, ((((int)(& std::get<1, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::substitution<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::substitution<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char()) + ((int)(& std::get<2, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::insertion<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::insertion<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char())) + ((int)(& std::get<3, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::deletion<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::deletion<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char())))’ from ‘int’ to ‘unsigned char’ inside { } [-Werror=narrowing]
             std::get<0>(out) = search_cfg::total<uint8_t>{std::min(255, static_cast<uint8_t>(std::get<1>(out))
             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       + static_cast<uint8_t>(std::get<2>(out))
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       + static_cast<uint8_t>(std::get<3>(out)))};
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

* [fix] warnings in search tests

```
In file included from /seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp:46,
                 from /seqan3/include/seqan3/search/algorithm/configuration/all.hpp:49,
                 from /seqan3/include/seqan3/search/algorithm/all.hpp:91,
                 from /seqan3/test/unit/search/search_test.cpp:40:
/seqan3/include/seqan3/search/algorithm/configuration/utility.hpp: In instantiation of ‘constexpr bool seqan3::contains(const seqan3::detail::configuration<configs_t ...>&) [with seqan3::search_cfg::id e = (seqan3::search_cfg::id)0; cfg_elements_t = {seqan3::detail::search_config_max_error_rate}]’:
/seqan3/include/seqan3/search/algorithm/search.hpp:84:54:   required from ‘auto seqan3::search(const index_t&, queries_t&&, const configuration_t&) [with index_t = seqan3::bi_fm_index<std::vector<seqan3::dna4> >; queries_t = const std::vector<std::vector<seqan3::dna4> >&; configuration_t = seqan3::detail::configuration<seqan3::detail::search_config_max_error_rate>]’
/seqan3/test/unit/search/search_test.cpp:125:5:   required from ‘void search_test_multiple_queries_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::bi_fm_index<std::vector<seqan3::dna4> >]’
/seqan3/test/unit/search/search_test.cpp:119:1:   required from here
/seqan3/include/seqan3/search/algorithm/configuration/utility.hpp:280:74: error: unused parameter ‘cfg’ [-Werror=unused-parameter]
 constexpr bool contains(detail::configuration<cfg_elements_t...> const & cfg) noexcept
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~

```

* [fix] warnings in search tests

```
In file included from /seqan3/test/unit/search/search_test.cpp:42:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/search/search_test.cpp:300:9:   required from ‘void search_test_search_strategy_best_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::fm_index<std::vector<seqan3::dna4> >]’
/seqan3/test/unit/search/search_test.cpp:291:1:   required from here
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1421:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~

```

* [fix] warnings in search tests

```
In file included from /seqan3/include/seqan3/search/fm_index/fm_index.hpp:53,
                 from /seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:46,
                 from /seqan3/include/seqan3/search/fm_index/all.hpp:73,
                 from /seqan3/include/seqan3/search/algorithm/search.hpp:44,
                 from /seqan3/include/seqan3/search/algorithm/all.hpp:92,
                 from /seqan3/test/unit/search/search_test.cpp:40:
/seqan3/include/seqan3/search/fm_index/fm_index_iterator.hpp: In member function ‘bool seqan3::fm_index_iterator<index_t>::extend_right(seq_t&&) [with seq_t = ranges::v3::iterator_range<__gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> >, __gnu_cxx::__normal_iterator<seqan3::dna4*, std::vector<seqan3::dna4> > >; index_t = seqan3::fm_index<std::vector<seqan3::dna4> >]’:
/seqan3/include/seqan3/search/fm_index/fm_index_iterator.hpp:356:9: error: ‘c’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         node = {_lb, _rb, last - first + node.depth, c};
         ^~~~

```

* [fix] warnings in search tests

```
In file included from /seqan3/test/unit/search/fm_index_iterator_test.cpp:45:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int]’:
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1449:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = long unsigned int; T2 = int; bool lhs_is_null_literal = false]’
/seqan3/test/unit/search/fm_index_iterator_test.cpp:136:5:   required from ‘void fm_index_iterator_test_extend_right_range_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::fm_index_iterator<seqan3::fm_index<std::vector<seqan3::dna4>, fm_index_byte_alphabet_traits> >]’
/seqan3/test/unit/search/fm_index_iterator_test.cpp:126:1:   required from here
/seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:1421:11: error: comparison of integer expressions of different signedness: ‘const long unsigned int’ and ‘const int’ [-Werror=sign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~

```

* Apply suggestions from code review

Co-Authored-By: marehr <marehr@users.noreply.github.com>