[FIX] cxx20: std::is_pod_v<int> is deprecated
```c++
seqan3/include/seqan3/core/pod_tuple.hpp:57:24: error: ‘std::is_pod_v<int>’ is deprecated: use is_standard_layout_v && is_trivial_v instead [-Werror=deprecated-declarations]
   57 |     static_assert(std::is_pod_v<type0>, SEQAN_NOT_POD);
      |                   ~~~~~^~~~~~~~~~~~~~~
```