[fix] clang: unused variables
```c++
seqan3/test/unit/range/container/aligned_allocator_test.cpp:68:42: error: unused variable 'alloc' [-Werror,-Wunused-variable]
    constexpr aligned_allocator<int, 16> alloc{};
                                         ^
seqan3/test/unit/range/container/aligned_allocator_test.cpp:74:34: error: unused variable 'float_alloc' [-Werror,-Wunused-variable]
    aligned_allocator<float, 16> float_alloc{int_alloc};
                                 ^
```