[FIX] gcc-12, error: ignoring return value of [...], declared with attribute ‘nodiscard’ [-Werror=unused-result]
```
In file included from /seqan3/include/seqan3/io/sam_file/header.hpp:21,
                 from /seqan3/test/unit/io/sam_file/sam_file_record_test.cpp:20:
/seqan3/include/seqan3/io/sam_file/detail/cigar.hpp: In instantiation of ‘std::tuple<std::vector<seqan3::cigar, std::allocator<seqan3::cigar> >, int, int> seqan3::detail::parse_cigar(cigar_input_type&&) [with cigar_input_type = std::basic_string_view<char>]’:
/seqan3/test/include/seqan3/test/literal/cigar_literal.hpp:24:51:   required from here
/seqan3/include/seqan3/io/sam_file/detail/cigar.hpp:154:26: error: ignoring return value of ‘constexpr _It std::ranges::__next_fn::operator()(_It) const [with _It = seqan3::detail::basic_iterator<seqan3::detail::single_pass_input_view<std::basic_string_view<char> > >]’, declared with attribute ‘nodiscard’ [-Werror=unused-result]
  154 |         std::ranges::next(std::ranges::begin(cigar_view));
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```