[fix] warnings in search tests
```
In file included from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:42:
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp: In instantiation of ‘auto seqan3::detail::search_scheme_block_info(const search_scheme_t&, size_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; size_t = long unsigned int]’:
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:222:65:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:118:45: error: narrowing conversion of ‘(((long unsigned int)query_length) % 1)’ from ‘long unsigned int’ to ‘uint8_t’ {aka ‘unsigned char’} inside { } [-Werror=narrowing]
     uint8_t const rest        {query_length % blocks};
                                ~~~~~~~~~~~~~^~~~~~~~
```