[FIX] relax seqan3::detail::algorithm_executor_blocking requirements to be C++20 compatible
```
In file included from /seqan3/test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:14:
/seqan3/include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp: In instantiation of ‘seqan3::detail::algorithm_executor_blocking<resource_t, algorithm_t, algorithm_result_t, execution_handler_t>::algorithm_executor_blocking(seqan3::detail::algorithm_executor_blocking<resource_t, algorithm_t, algorithm_result_t, execution_handler_t>&&) [with resource_t = std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&; algorithm_t = std::function<void(std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, std::function<void(long unsigned int)>)>; algorithm_result_t = long unsigned int; execution_handler_t = seqan3::detail::execution_handler_sequential]’:
/seqan3/test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:143:16:   required from ‘void algorithm_executor_blocking_test_move_assignment_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::detail::execution_handler_sequential]’
/seqan3/test/unit/core/algorithm/detail/algorithm_executor_blocking_test.cpp:125:1:   required from here
/seqan3/include/seqan3/core/algorithm/detail/algorithm_executor_blocking.hpp:344:19: error: could not convert ‘<brace-enclosed initializer list>()’ from ‘<brace-enclosed initializer list>’ to ‘seqan3::detail::algorithm_executor_blocking<std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&, std::function<void(std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >, std::function<void(long unsigned int)>)>, long unsigned int, seqan3::detail::execution_handler_sequential>::resource_type’ {aka ‘std::ranges::ref_view<std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > > >’}
  344 |     resource_type resource{};
      |                   ^~~~~~~~
      |                   |
      |                   <brace-enclosed initializer list>
```

Note this needed some more changes to the move- assignment and
constructor, as we otherwise would do operations on a possible stale iterator.