[FIX] gcc8: declare_view_functor_type error
In file included from /seqan3/test/unit/range/view/declare_view_functor_type_test.cpp:40:
/seqan3/include/seqan3/range/view/detail.hpp: In instantiation of ‘auto seqan3::detail::declare_view_functor_type<view_type>::auxiliary_functor_t<arg_types>::explode(urng_t&&, std::index_sequence<Is ...>&) [with urng_t = std::vector<int>&; long unsigned int ...Is = {0}; arg_types = {test_param}; view_type = test_view_args; std::index_sequence<Is ...> = std::integer_sequence<long unsigned int, 0>]’:
/seqan3/include/seqan3/range/view/detail.hpp:175:106:   required from ‘auto seqan3::detail::declare_view_functor_type<view_type>::auxiliary_functor_t<arg_types>::operator()(urng_t&&) requires  sizeof ... (arg_types ...) > 0 and <valid-expression ({(declval<urng_t>)(), (declval<arg_types>)()...})> [with urng_t = std::vector<int>&; arg_types = {test_param}; view_type = test_view_args]’
/seqan3/include/seqan3/range/view/detail.hpp:283:29:   required from ‘auto seqan3::detail::operator|(urng_t&&, seqan3::detail::declare_view_functor_type<view_type>::auxiliary_functor_t<arg_types ...>&&) requires  sizeof ... (arg_types ...) > 0 and <valid-expression ({(declval<urng_t>)(), (declval<arg_types>)()...})> [with urng_t = std::vector<int>&; arg_types = {test_param}; view_type = test_view_args]’
/seqan3/test/unit/range/view/declare_view_functor_type_test.cpp:132:38:   required from here
/seqan3/include/seqan3/range/view/detail.hpp:186:83: error: wrong number of template arguments (2, should be 1)
             using parent_type = declare_view_functor_type<view_type, arg_types...>;
                                                                                   ^
/seqan3/include/seqan3/range/view/detail.hpp:98:8: note: provided for ‘template<template<class> class view_type> struct seqan3::detail::declare_view_functor_type’
 struct declare_view_functor_type
        ^~~~~~~~~~~~~~~~~~~~~~~~~
/seqan3/test/unit/range/view/declare_view_functor_type_test.cpp: In member function ‘virtual void declare_view_functor_type_with_args_pipe_interface_Test::TestBody()’:
/seqan3/test/unit/range/view/declare_view_functor_type_test.cpp:132:10: error: ‘void v’ has incomplete type
     auto v = urange | f(test_param{7});
          ^
In file included from /seqan3-build/gcc-8-release/vendor/googletest/googletest/include/gtest/gtest.h:58,
                 from /seqan3/test/unit/range/view/declare_view_functor_type_test.cpp:38:
/seqan3/test/unit/range/view/declare_view_functor_type_test.cpp:134:23: error: template argument 1 is invalid
     EXPECT_TRUE((std::is_same_v<decltype(v), test_view_args<std::vector<int>>>));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~