[FIX] clang+gcc9: error: requires clause differs in template redeclaration (friend)
```
/seqan3/include/seqan3/alignment/matrix/detail/trace_iterator_base.hpp:71:23: error: requires clause differs in template redeclaration
        requires std::constructible_from<derived_t, other_derived_t> &&
                      ^

```