[fix] warnings in search tests
```
In file included from /seqan3/test/unit/search/search_scheme_algorithm_test.cpp:42:
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp: In instantiation of ‘bool seqan3::detail::search_ss(iterator_t, query_t&, typename iterator_t::size_type, typename iterator_t::size_type, uint8_t, uint8_t, bool, const search_t&, const blocks_length_t&, seqan3::detail::search_param, delegate_t&&) [with bool abort_on_hit = false; iterator_t = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; query_t = std::vector<seqan3::dna4>; search_t = seqan3::detail::search<1>; blocks_length_t = std::array<long unsigned int, 1>; delegate_t = test_search_hamming(auto:23, const text_t&, const auto:24&, uint64_t, const std::vector<unsigned char>&, time_t, const auto:25&, const auto:26&, uint64_t) [with text_t = std::vector<seqan3::dna4>; auto:23 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; auto:24 = seqan3::detail::search<1>; auto:25 = std::array<long unsigned int, 1>; auto:26 = std::vector<long unsigned int>; uint64_t = long unsigned int; time_t = long int]::<lambda(const auto:28&)>&; typename iterator_t::size_type = long unsigned int; uint8_t = unsigned char]’:
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:161:29:   required from ‘void test_search_hamming(auto:23, const text_t&, const auto:24&, uint64_t, const std::vector<unsigned char>&, time_t, const auto:25&, const auto:26&, uint64_t) [with text_t = std::vector<seqan3::dna4>; auto:23 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, seqan3::bi_fm_index_default_traits> >; auto:24 = seqan3::detail::search<1>; auto:25 = std::array<long unsigned int, 1>; auto:26 = std::vector<long unsigned int>; uint64_t = long unsigned int; time_t = long int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:233:44:   required from ‘void test_search_scheme_hamming(const search_scheme_t&, time_t, uint64_t) [with search_scheme_t = std::array<seqan3::detail::search<1>, 1>; time_t = long int; uint64_t = long unsigned int]’
/seqan3/test/unit/search/search_scheme_algorithm_test.cpp:317:104:   required from here
/seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:407:45: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
     else if ((max_error_left_in_block == 0) && (rb - lb - 1 != blocks_length[block_id]) ||
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```