[TEST] don't import the seqan3 namespace in test templates
Adding `#include <seqan3/core/concept/core_language.hpp>` to `include/seqan3/alphabet/concept.hpp` shows the following error:

```terminal
In file included from seqan3/include/seqan3/std/concepts:25,
                 from seqan3/include/seqan3/alphabet/exception.hpp:19,
                 from seqan3/include/seqan3/alphabet/concept.hpp:15,
                 from seqan3/test/unit/alphabet/gap/gap_test.cpp:12:
seqan3/submodules/range-v3/include/range/v3/action/concepts.hpp:151:5: error: reference to ‘implicitly_convertible_to’ is ambiguous
  151 |     CPP_def
      |     ^~~~~~~
In file included from seqan3/include/seqan3/alphabet/concept.hpp:17,
                 from seqan3/test/unit/alphabet/gap/gap_test.cpp:12:
seqan3/include/seqan3/core/concept/core_language.hpp:114:16: note: candidates are: ‘template<class t, class u> concept const bool seqan3::implicitly_convertible_to<t, u>’
  114 | SEQAN3_CONCEPT implicitly_convertible_to = std::is_convertible_v<t, u>;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from seqan3/include/seqan3/std/concepts:25,
                 from seqan3/include/seqan3/alphabet/exception.hpp:19,
                 from seqan3/include/seqan3/alphabet/concept.hpp:15,
                 from seqan3/test/unit/alphabet/gap/gap_test.cpp:12:
seqan3/submodules/range-v3/include/concepts/concepts.hpp:929:9: note:                 ‘template<class From, class To> concept const bool concepts::defs::_eager_::implicitly_convertible_to<From, To>’
  929 |         CPP_def
      |         ^~~~~~~
```

This was caused, because in test_templates we use `using seqan3;`, which makes `seqan3::implictly_convertible_to` public (globally).

This is a problem, because we include after `using seqan3;` more headers and they now see the polluted `implictly_convertible_to` concept.

This could be resolved by removing the `using seqan3` line.