[FIX] cxx20: add missing includes
* cxx20: missing include <array>
* cxx20: missing include <cassert>
* cxx20: missing include <optional>
* cxx20: missing include <stdexcept>
* cxx20: missing include <unordered_map>
* cxx20: missing include <range/v3/view/all.hpp>
* cxx20: missing include platform.hpp
* cxx20: missing include type_traits/basic.hpp

```c++
seqan3/include/seqan3/core/parallel/detail/reader_writer_manager.hpp:317:10: error: ‘function’ in namespace ‘std’ does not name a template type
  317 |     std::function<void()>                                               completion_fn;
      |          ^~~~~~~~
```

```c++
include/seqan3/core/detail/int_types-1.cpp:8:2: error: #error "Your header file is missing #include <seqan3/core/platform.hpp>"
    8 | #error "Your header file is missing #include <seqan3/core/platform.hpp>"
      |  ^~~~~
```

```c++
seqan3/include/seqan3/alignment/configuration/align_config_aligned_ends.hpp:324:9: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
  324 |         assert(pos < values.size());
      |         ^~~~~~
```

```c++
seqan3/include/seqan3/alignment/matrix/detail/alignment_trace_matrix_proxy.hpp:36:19: error: ‘decays_to_ignore_v’ was not declared in this scope
   36 |                   decays_to_ignore_v<trace_type>,
      |                   ^~~~~~~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/core/simd/detail/simd_algorithm_sse4.hpp:35:13: error: variable or field ‘transpose_matrix_sse4’ declared void
   35 | inline void transpose_matrix_sse4(std::array<simd_t, simd_traits<simd_t>::length> & matrix);
      |             ^~~~~~~~~~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/argument_parser/auxiliary.hpp:73:6: error: ‘unordered_map’ in namespace ‘std’ does not name a template type
   73 | std::unordered_map<std::string_view, t> enumeration_names(t) = delete;
      |      ^~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/core/detail/debug_stream_variant.hpp:37:50: error: ‘remove_cvref_t’ was not declared in this scope; did you mean ‘std::remove_cvref_t’?
   37 |     requires detail::is_type_specialisation_of_v<remove_cvref_t<variant_type>, std::variant>
      |                                                  ^~~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/core/simd/detail/simd_algorithm_avx2.hpp:35:13: error: variable or field ‘transpose_matrix_avx2’ declared void
   35 | inline void transpose_matrix_avx2(std::array<simd_t, simd_traits<simd_t>::length> & matrix);
      |             ^~~~~~~~~~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/core/simd/detail/simd_algorithm_avx512.hpp:35:13: error: variable or field ‘transpose_matrix_avx512’ declared void
   35 | inline void transpose_matrix_avx512(std::array<simd_t, simd_traits<simd_t>::length> & matrix);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
```

```c++
seqan3/core/math-1.cpp:8:2: error: #error "Your header file is missing #include <seqan3/core/platform.hpp>"
    8 | #error "Your header file is missing #include <seqan3/core/platform.hpp>"
      |  ^~~~~
```

```c++
seqan3/include/seqan3/core/detail/debug_stream_optional.hpp:33:26: error: ‘remove_cvref_t’ was not declared in this scope; did you mean ‘std::remove_cvref_t’?
   33 |    requires std::same_as<remove_cvref_t<optional_type>, std::nullopt_t>
      |                          ^~~~~~~~~~~~~~
```

```c++
seqan3/include/seqan3/core/math.hpp:62:28: error: ‘underflow_error’ is not a member of ‘std’
   62 |                 throw std::underflow_error{error_message + " underflow."};
      |                            ^~~~~~~~~~~~~~~
```

```c++
include/seqan3/alignment/pairwise/alignment_result.hpp:34:40: error: ‘nullopt_t’ in namespace ‘std’ does not name a type; did you mean ‘nullptr_t’?
   34 |           typename back_coord_t = std::nullopt_t *,
      |                                        ^~~~~~~~~
```

```c++
seqan3/test/snippet/core/type_traits/function_traits.cpp:9:5: error: ‘assert’ was not declared in this scope
    9 |     assert(position < sequence.size());
      |     ^~~~~~
```

```c++
seqan3/doc/howto/write_an_alphabet/dna2_semialphabet.cpp:26:9: error: ‘assert’ was not declared in this scope
   26 |         assert(rk < alphabet_size);
      |         ^~~~~~
```

```c++
seqan3/doc/howto/write_an_alphabet/dna2_alphabet.cpp:26:9: error: ‘assert’ was not declared in this scope
   26 |         assert(rk < alphabet_size);
      |         ^~~~~~
```