[FIX] add ; after requires expression
```
In file included from /seqan3/include/seqan3/search/algorithm/detail/search_scheme_algorithm.hpp:22,
                 from /seqan3-build/header-git-std17/seqan3_header_test_files/seqan3/search/algorithm/detail/search_scheme_algorithm-2.cpp:2:
/seqan3/include/seqan3/search/fm_index/concept.hpp:158:74: error: expected ‘;’ before ‘}’ token
  158 |     requires requires (typename t::index_type const index) { { t(index) } };
      |                                                                          ^~
      |                                                                          ;
```