[FIX] clang+gcc9: error: requires clause differs in template redeclaration (friend)
```
/seqan3/include/seqan3/alignment/matrix/detail/two_dimensional_matrix.hpp:339:18: error: requires clause differs in template redeclaration
        requires is_value_specialisation_of_v<derived_t, basic_iterator> && (other_order == order)
                 ^
```