[FIX] relax seqan3::detail::aligned_sequence_builder requirements to be C++20 compatible
```
In file included from /seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/gtest.h:62,
                 from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:8:
/seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/internal/gtest-internal.h: In instantiation of ‘testing::Test* testing::internal::TestFactoryImpl<TestClass>::CreateTest() [with TestClass = aligned_sequence_builder_fixture_issue1921_Test<std::pair<std::__cxx11::list<seqan3::dna4>&, std::__cxx11::list<seqan3::dna4>&> >]’:
/seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/internal/gtest-internal.h:472:9:   required from here
/seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/internal/gtest-internal.h:472:40: error: use of deleted function ‘aligned_sequence_builder_fixture_issue1921_Test<std::pair<std::__cxx11::list<seqan3::dna4>&, std::__cxx11::list<seqan3::dna4>&> >::aligned_sequence_builder_fixture_issue1921_Test()’
  472 |   Test* CreateTest() override { return new TestClass; }
      |                                        ^~~~~~~~~~~~~
In file included from /seqan3-build/gcc-git-debug-std20/_deps/gtest_fetch_content-src/googletest/include/gtest/gtest.h:62,
                 from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:8:
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:292:12: note: ‘aligned_sequence_builder_fixture_issue1921_Test<std::pair<std::__cxx11::list<seqan3::dna4>&, std::__cxx11::list<seqan3::dna4>&> >::aligned_sequence_builder_fixture_issue1921_Test()’ is implicitly deleted because the default definition would be ill-formed:
  292 | TYPED_TEST(aligned_sequence_builder_fixture, issue1921)
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:292:12: error: use of deleted function ‘aligned_sequence_builder_fixture<std::pair<std::__cxx11::list<seqan3::dna4>&, std::__cxx11::list<seqan3::dna4>&> >::aligned_sequence_builder_fixture()’
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:26:8: note: ‘aligned_sequence_builder_fixture<std::pair<std::__cxx11::list<seqan3::dna4>&, std::__cxx11::list<seqan3::dna4>&> >::aligned_sequence_builder_fixture()’ is implicitly deleted because the default definition would be ill-formed:
   26 | struct aligned_sequence_builder_fixture : ::testing::Test
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:26:8: error: use of deleted function ‘constexpr seqan3::detail::aligned_sequence_builder<fst_sequence_t, sec_sequence_t>::aligned_sequence_builder() [with fst_sequence_t = std::__cxx11::list<seqan3::dna4>&; sec_sequence_t = std::__cxx11::list<seqan3::dna4>&]’
In file included from /seqan3/test/unit/alignment/matrix/detail/aligned_sequence_builder_test.cpp:14:
/seqan3/include/seqan3/alignment/matrix/detail/aligned_sequence_builder.hpp:137:15: note: ‘constexpr seqan3::detail::aligned_sequence_builder<fst_sequence_t, sec_sequence_t>::aligned_sequence_builder() [with fst_sequence_t = std::__cxx11::list<seqan3::dna4>&; sec_sequence_t = std::__cxx11::list<seqan3::dna4>&]’ is implicitly deleted because the default definition would be ill-formed:
  137 |     constexpr aligned_sequence_builder() = default; //!< Defaulted.
      |               ^~~~~~~~~~~~~~~~~~~~~~~~

```