[fix] warnings in search tests
```log
In file included from /home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/bi_fm_index.hpp:47:0,
                 from /home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/all.hpp:73,
                 from /home/travis/build/seqan/seqan3/test/unit/search/fm_index_iterator_test.cpp:42:
/home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp: In instantiation of ‘bool seqan3::bi_fm_index_iterator<index_t>::operator==(const seqan3::bi_fm_index_iterator<index_t>&) const [with index_t = seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits>]’:
/home/travis/build/seqan/seqan3-build/vendor/googletest/googletest/include/gtest/gtest.h:1436:11:   required from ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits> >; T2 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits> >]’
/home/travis/build/seqan/seqan3-build/vendor/googletest/googletest/include/gtest/gtest.h:1464:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits> >; T2 = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits> >; bool lhs_is_null_literal = false]’
/home/travis/build/seqan/seqan3/test/unit/search/fm_index_iterator_test.cpp:293:186:   required from ‘void fm_index_iterator_test_incomplete_alphabet_Test<gtest_TypeParam_>::TestBody() [with gtest_TypeParam_ = seqan3::bi_fm_index_iterator<seqan3::bi_fm_index<std::vector<seqan3::dna4>, bi_fm_index_byte_alphabet_traits> >]’
/home/travis/build/seqan/seqan3/test/unit/search/fm_index_iterator_test.cpp:339:1:   required from here
/home/travis/build/seqan/seqan3/include/seqan3/search/fm_index/bi_fm_index_iterator.hpp:295:152: error: suggest parentheses around ‘&&’ within ‘||’ [-Werror=parentheses]
         assert(!(fwd_lb == rhs.fwd_lb && fwd_rb == rhs.fwd_rb && depth == rhs.depth) ||
                                                                                                                                                        ^

```