[fix] clang: unused variables
```c++
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:82:66: error: unused variable 'it' [-Werror,-Wunused-variable]
    seqan3::detail::random_access_iterator<std::vector<uint8_t>> it;
                                                                 ^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:83:72: error: unused variable 'it2' [-Werror,-Wunused-variable]
    seqan3::detail::random_access_iterator<std::vector<uint8_t> const> it2;
                                                                       ^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:128:66: error: unused variable 'it_derivate' [-Werror,-Wunused-variable]
    seqan3::detail::random_access_iterator<std::vector<uint8_t>> it_derivate(it_base);
                                                                 ^
/seqan3/test/unit/range/detail/random_access_iterator_test.cpp:131:72: error: unused variable 'it_derivate2' [-Werror,-Wunused-variable]
    seqan3::detail::random_access_iterator<std::vector<uint8_t> const> it_derivate2(it_base2);
                                                                       ^
```