[FIX] clang+gcc9: error: requires clause differs in template redeclaration (friend)
```
/seqan3/include/seqan3/alignment/matrix/detail/two_dimensional_matrix_iterator_base.hpp:85:18: error: requires clause differs in template redeclaration
        requires (order == other_order)
                 ^
```