[fix] warnings in search tests
```
In file included from /seqan3/include/seqan3/search/algorithm/configuration/all.hpp:49,
                 from /seqan3/include/seqan3/search/algorithm/all.hpp:91,
                 from /seqan3/test/unit/search/search_test.cpp:40:
/seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp: In instantiation of ‘constexpr auto seqan3::detail::search_config_max_error_adaptor::invoke(configuration_t&&, error_types_t&& ...) const [with configuration_t = seqan3::detail::configuration<>; error_types_t = {const seqan3::search_cfg::substitution<unsigned char>&}]’:
/seqan3/include/seqan3/core/algorithm/configuration.hpp:394:93:   required from ‘constexpr auto seqan3::detail::configuration_fn_base<derived_fn_t>::operator()(configuration_t&&, args_t&& ...) const requires  is_algorithm_configuration_v<typename std::remove_cv<typename std::remove_reference<_SrcTuple>::type>::remove_cvref_t> [with configuration_t = seqan3::detail::configuration<>; args_t = {const seqan3::search_cfg::substitution<unsigned char>&}; derived_fn_t = seqan3::detail::search_config_max_error_adaptor]’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:514:27:   required from ‘constexpr auto seqan3::detail::configuration_fn_proxy<derived_t, args_t>::explode(configuration_t&&, std::index_sequence<Is ...>) const & [with configuration_t = seqan3::detail::configuration<>; long unsigned int ...Is = {0}; derived_t = seqan3::detail::search_config_max_error_adaptor; args_t = {seqan3::search_cfg::substitution<unsigned char>}; std::index_sequence<Is ...> = std::integer_sequence<long unsigned int, 0>]’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:528:105:   required from ‘constexpr auto seqan3::detail::configuration_fn_proxy<derived_t, args_t>::operator()(configuration_t&&) && [with configuration_t = seqan3::detail::configuration<>; derived_t = seqan3::detail::search_config_max_error_adaptor; args_t = {seqan3::search_cfg::substitution<unsigned char>}]’
/usr/include/c++/8.2.1/type_traits:2283:26:   required by substitution of ‘template<class _Fn, class ... _Args> static std::__result_of_success<decltype (declval<_Fn>()((declval<_Args>)()...)), std::__invoke_other> std::__result_of_other_impl::_S_test(int) [with _Fn = seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >; _Args = {seqan3::detail::configuration<>}]’
/usr/include/c++/8.2.1/type_traits:2294:55:   required from ‘struct std::__result_of_impl<false, false, seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/usr/include/c++/8.2.1/type_traits:2299:12:   required from ‘struct std::__invoke_result<seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/usr/include/c++/8.2.1/type_traits:2685:12:   required from ‘struct std::invoke_result<seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >, seqan3::detail::configuration<> >’
/seqan3/include/seqan3/core/algorithm/configuration.hpp:299:1:   required by substitution of ‘template<class cfg_fn_t>  requires  is_type_specialisation_of_v<typename std::remove_reference::remove_reference_t, seqan3::detail::configuration_fn_proxy> or is_base_of_v<seqan3::detail::configuration_fn_base<typename std::remove_cv<typename std::remove_reference<_Tp>::type>::type>, typename std::remove_cv<typename std::remove_reference<_Tp>::type>::remove_cvref_t> seqan3::detail::configuration(cfg_fn_t&&)-> seqan3::detail::configuration<typename meta::v1::detail::front_<typename seqan3::detail::tuple_type_list<typename std::invoke_result<typename std::remove_reference<_Tp>::type, seqan3::detail::configuration<> >::type::base_type>::type>::type> [with cfg_fn_t = seqan3::detail::configuration_fn_proxy<seqan3::detail::search_config_max_error_adaptor, seqan3::search_cfg::substitution<unsigned char> >]’
/seqan3/test/unit/search/search_test.cpp:190:68:   required from here
/seqan3/include/seqan3/search/algorithm/configuration/max_error.hpp:126:30: error: narrowing conversion of ‘(int)std::min<int>(255, ((((int)(& std::get<1, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::substitution<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::substitution<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char()) + ((int)(& std::get<2, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::insertion<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::insertion<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char())) + ((int)(& std::get<3, seqan3::search_cfg::total<unsigned char>, seqan3::search_cfg::substitution<unsigned char>, seqan3::search_cfg::insertion<unsigned char>, seqan3::search_cfg::deletion<unsigned char> >(out))->seqan3::search_cfg::deletion<unsigned char>::<anonymous>.seqan3::detail::strong_type<unsigned char, seqan3::search_cfg::deletion<unsigned char>, (seqan3::detail::strong_type_skill)65536>::operator unsigned char())))’ from ‘int’ to ‘unsigned char’ inside { } [-Werror=narrowing]
             std::get<0>(out) = search_cfg::total<uint8_t>{std::min(255, static_cast<uint8_t>(std::get<1>(out))
             ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       + static_cast<uint8_t>(std::get<2>(out))
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       + static_cast<uint8_t>(std::get<3>(out)))};
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```